### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Jameel9** [deeplab-ai/denvis#48]
Hello Sir

I hope you are doing well

Firstly, thank you for this work that is a really promising tool for drug discovery arena. 
I do have an issue on how to use DENVIS to screen my collection of compounds on a specific target protein. I think the addition of few lines in README file about usage and optional arguments would be a great idea. 

Thnx.

**Comment by agamemnonc** [comment]
Thank you very much for your interest in our work @Jameel9. 

Could you please provide some more details on which part you had difficulty in using our REST APi? Have you followed the guidelines in Sections [1](https://github.com/deeplab-ai/denvis#1-data) and [2](https://github.com/deeplab-ai/denvis#1-data) of the README file? 

If you can provide some more information about what you would like us to add in the README file we will consider including it.
@nanton96 FYI

**Comment by Jameel9** [comment]
I actually went through the file. I am not planning to train models from scratch. I just want to use the pre-trained models (on Gogle Colab) to reduce the number of molecules to be abalysed later.. (I have ~ 1M compounds). 
I want to run a DL-based screening to obtain the top 1000 or 2000 compounds to be handled easily in the subsequent analyses.

**Comment by agamemnonc** [comment]
As per the first paragraph in our README file, I am afraid that we currently restrict the number of compounds per query to 100, due to limited computational resources from our side. We may consider increasing this figure in the future, but I am afraid we cannot promise it right now.

**Comment by agamemnonc** [comment]
Just to clairfy @Jameel9, it is not possibly to use our pre-trained models to run inference outside our REST API (e.g. locally or on google colab).
